// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"sync"
)

// Ensure, that StorerMock does implement Storer.
// If this is not the case, regenerate this file with moq.
var _ Storer = &StorerMock{}

// StorerMock is a mock implementation of Storer.
//
//	func TestSomethingThatUsesStorer(t *testing.T) {
//
//		// make and configure a mocked Storer
//		mockedStorer := &StorerMock{
//			createAuthorizationFunc: func(authorization *Authorization) error {
//				panic("mock out the createAuthorization method")
//			},
//			createRequestFunc: func(request *Request) error {
//				panic("mock out the createRequest method")
//			},
//			findAuthorizationFunc: func(s string) (*Authorization, error) {
//				panic("mock out the findAuthorization method")
//			},
//			findRequestFunc: func(s string) (*Request, error) {
//				panic("mock out the findRequest method")
//			},
//		}
//
//		// use mockedStorer in code that requires Storer
//		// and then make assertions.
//
//	}
type StorerMock struct {
	// createAuthorizationFunc mocks the createAuthorization method.
	createAuthorizationFunc func(authorization *Authorization) error

	// createRequestFunc mocks the createRequest method.
	createRequestFunc func(request *Request) error

	// findAuthorizationFunc mocks the findAuthorization method.
	findAuthorizationFunc func(s string) (*Authorization, error)

	// findRequestFunc mocks the findRequest method.
	findRequestFunc func(s string) (*Request, error)

	// calls tracks calls to the methods.
	calls struct {
		// createAuthorization holds details about calls to the createAuthorization method.
		createAuthorization []struct {
			// Authorization is the authorization argument value.
			Authorization *Authorization
		}
		// createRequest holds details about calls to the createRequest method.
		createRequest []struct {
			// Request is the request argument value.
			Request *Request
		}
		// findAuthorization holds details about calls to the findAuthorization method.
		findAuthorization []struct {
			// S is the s argument value.
			S string
		}
		// findRequest holds details about calls to the findRequest method.
		findRequest []struct {
			// S is the s argument value.
			S string
		}
	}
	lockcreateAuthorization sync.RWMutex
	lockcreateRequest       sync.RWMutex
	lockfindAuthorization   sync.RWMutex
	lockfindRequest         sync.RWMutex
}

// createAuthorization calls createAuthorizationFunc.
func (mock *StorerMock) createAuthorization(authorization *Authorization) error {
	if mock.createAuthorizationFunc == nil {
		panic("StorerMock.createAuthorizationFunc: method is nil but Storer.createAuthorization was just called")
	}
	callInfo := struct {
		Authorization *Authorization
	}{
		Authorization: authorization,
	}
	mock.lockcreateAuthorization.Lock()
	mock.calls.createAuthorization = append(mock.calls.createAuthorization, callInfo)
	mock.lockcreateAuthorization.Unlock()
	return mock.createAuthorizationFunc(authorization)
}

// createAuthorizationCalls gets all the calls that were made to createAuthorization.
// Check the length with:
//
//	len(mockedStorer.createAuthorizationCalls())
func (mock *StorerMock) createAuthorizationCalls() []struct {
	Authorization *Authorization
} {
	var calls []struct {
		Authorization *Authorization
	}
	mock.lockcreateAuthorization.RLock()
	calls = mock.calls.createAuthorization
	mock.lockcreateAuthorization.RUnlock()
	return calls
}

// createRequest calls createRequestFunc.
func (mock *StorerMock) createRequest(request *Request) error {
	if mock.createRequestFunc == nil {
		panic("StorerMock.createRequestFunc: method is nil but Storer.createRequest was just called")
	}
	callInfo := struct {
		Request *Request
	}{
		Request: request,
	}
	mock.lockcreateRequest.Lock()
	mock.calls.createRequest = append(mock.calls.createRequest, callInfo)
	mock.lockcreateRequest.Unlock()
	return mock.createRequestFunc(request)
}

// createRequestCalls gets all the calls that were made to createRequest.
// Check the length with:
//
//	len(mockedStorer.createRequestCalls())
func (mock *StorerMock) createRequestCalls() []struct {
	Request *Request
} {
	var calls []struct {
		Request *Request
	}
	mock.lockcreateRequest.RLock()
	calls = mock.calls.createRequest
	mock.lockcreateRequest.RUnlock()
	return calls
}

// findAuthorization calls findAuthorizationFunc.
func (mock *StorerMock) findAuthorization(s string) (*Authorization, error) {
	if mock.findAuthorizationFunc == nil {
		panic("StorerMock.findAuthorizationFunc: method is nil but Storer.findAuthorization was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockfindAuthorization.Lock()
	mock.calls.findAuthorization = append(mock.calls.findAuthorization, callInfo)
	mock.lockfindAuthorization.Unlock()
	return mock.findAuthorizationFunc(s)
}

// findAuthorizationCalls gets all the calls that were made to findAuthorization.
// Check the length with:
//
//	len(mockedStorer.findAuthorizationCalls())
func (mock *StorerMock) findAuthorizationCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockfindAuthorization.RLock()
	calls = mock.calls.findAuthorization
	mock.lockfindAuthorization.RUnlock()
	return calls
}

// findRequest calls findRequestFunc.
func (mock *StorerMock) findRequest(s string) (*Request, error) {
	if mock.findRequestFunc == nil {
		panic("StorerMock.findRequestFunc: method is nil but Storer.findRequest was just called")
	}
	callInfo := struct {
		S string
	}{
		S: s,
	}
	mock.lockfindRequest.Lock()
	mock.calls.findRequest = append(mock.calls.findRequest, callInfo)
	mock.lockfindRequest.Unlock()
	return mock.findRequestFunc(s)
}

// findRequestCalls gets all the calls that were made to findRequest.
// Check the length with:
//
//	len(mockedStorer.findRequestCalls())
func (mock *StorerMock) findRequestCalls() []struct {
	S string
} {
	var calls []struct {
		S string
	}
	mock.lockfindRequest.RLock()
	calls = mock.calls.findRequest
	mock.lockfindRequest.RUnlock()
	return calls
}
