import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";

export default function Home() {
  const handleMessage = (event) => {
    if (event && event.data) {
      const evtIn =
        typeof event.data === "string" ? JSON.parse(event.data) : event.data;
      if (evtIn.name) {
        console.log(`inside: ${evtIn.name}, value: ${evtIn.value}`);
        const evtOut = { name: "sendOut" };
        parent.postMessage(JSON.stringify(evtOut), "*");
      }
    }
  };

  useEffect(() => {
    window.addEventListener("message", handleMessage);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>hello</main>
    </div>
  );
}
